import os
from pathlib import Path
import helper_functions
helper_functions.load_env()
from run_logging import get_logger, log_step, setup_error_logging

logger = get_logger(__name__)
logger.info("module loaded")
setup_error_logging()  # warnings + uncaught exceptions → logs/errors.log

import messenger
import feedback_collector
import task

import json
import time as _time
import requests
import copy
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_bolt.adapter.flask import SlackRequestHandler
from datetime import date, datetime


### ### CONSTANTS ### ###
DB_NAME = helper_functions.get_env("DB_NAME", "")

EMOJI_DICT = {0: '🪴', 
                1: '🌺', 
                2: '🍀', 
                3: '✨',
                4: '🐨', 
                5: '🐶',
                6: '🐱',
                7: '🦔',
                8: '🐱',
                9: '🪴', 
}


## ### LOAD IN MESSAGE BLOCKS ### ###
BLOCK_MESSAGES_DIR = Path(__file__).resolve().parent / "block_messages"

with (BLOCK_MESSAGES_DIR / "default_btn.json").open("r", encoding="utf-8") as infile:
    default_btn = json.load(infile)

with (BLOCK_MESSAGES_DIR / "help_block.json").open("r", encoding="utf-8") as infile:
    info_page = json.load(infile)

with (BLOCK_MESSAGES_DIR / "sample_task.json").open("r", encoding="utf-8") as infile:
    sample_task = json.load(infile)

with (BLOCK_MESSAGES_DIR / "onboarding_block.json").open("r", encoding="utf-8") as infile:
    onboarding = json.load(infile)

with (BLOCK_MESSAGES_DIR / "headers.json").open("r", encoding="utf-8") as infile:
    block_headers = json.load(infile)


### ### INITIALIZE BOLT APP ### ###
# Initialize app, socket mode handler, & client
BOT_TOKEN = helper_functions.get_env("SLACK_BOT_TOKEN") or helper_functions.get_env("TASK_BOT_TOKEN")
if not BOT_TOKEN:
    raise RuntimeError("SLACK_BOT_TOKEN is not set. Check your .env file.")

SLACK_APP_TOKEN = helper_functions.get_env("SLACK_APP_TOKEN")
if not SLACK_APP_TOKEN:
    raise RuntimeError("SLACK_APP_TOKEN is not set. Check your .env file.")

SIGNING_SECRET = helper_functions.get_env("TASK_BOT_SIGNING_SECRET")
if SIGNING_SECRET:
    app = App(token=BOT_TOKEN, signing_secret=SIGNING_SECRET)
else:
    app = App(token=BOT_TOKEN)
handler = SlackRequestHandler(app)
client = WebClient(token=BOT_TOKEN)

# Get the bot id
BOT_ID = client.api_call("auth.test")['user_id']



### ### HELPER FUNCTIONS ### ####
def _get_dm_channel_id(user_id: str) -> str:
    response = client.conversations_open(users=[user_id])
    return response["channel"]["id"]


def send_messages(user_id, block = None, text = None):
    channel_id = _get_dm_channel_id(user_id)
    client.chat_postMessage(channel=channel_id, blocks = block, text=text)
    return

def send_welcome_message(users_list) -> None:
    '''
    Takes   A list containing all user ids or a dictionary with user ids as its keys. 
            currently using users_store returned by get_all_users_info()
    Sends welcoming message to all users
    '''
    active_users = messenger.get_active_users_list()
    for user_id in users_list:
        if BOT_ID != user_id and user_id in active_users:      
            try:
                print(f'IN Welcome: {user_id}', datetime.now())
                channel_id = _get_dm_channel_id(user_id)
                client.chat_postMessage(channel=channel_id, blocks = onboarding['blocks'], text="Welcome to Snap'N'Go!")
                print("Welcome!")
            except SlackApiError as e:
                assert e.response["ok"] is False and e.response["error"], f"Got an error: {e.response['error']}"

def send_tasks(assignments_dict) -> None:
    log_step(
        logger,
        "interaction send_tasks start",
        users=len(assignments_dict) if assignments_dict else 0,
        user_ids=list(assignments_dict.keys())[:20] if assignments_dict else [],
    )
    '''
    * Message users to give them new tasks *
    Takes the assignments dictionary generated by getAssignments() in messenger
    Format the tasks each user get into block messages. Send them to each 
        user respectively
    Returns nothing
    ''' 
    active_users = messenger.get_active_users_list()
    for user_id in assignments_dict:
        print(f'IN SEND TASKS: {user_id}', datetime.now())
        if BOT_ID != user_id and user_id in active_users:   
            try:
                channel_id = _get_dm_channel_id(user_id)
                for task_info in assignments_dict[user_id]:
                    task_type = task_info[7] if len(task_info) > 7 else "data_collection"
                    if task_type == "verification":
                        assignment_id = task_info[8]
                        context = feedback_collector.get_verification_context(assignment_id)
                        if context and context.get("image_path"):
                            try:
                                client.files_upload_v2(
                                    channel=channel_id,
                                    file=context["image_path"],
                                    title="Submission image",
                                )
                            except Exception as exc:
                                print(f"Failed to upload image for verification task {task_info[0]}: {exc}")
                        block = feedback_collector.build_verification_blocks(
                            assignment_id,
                            task_info[0],
                            image_url=None,
                        )
                        client.chat_postMessage(channel=channel_id, blocks=block, text="Verification task")
                        print("Send verification task!")
                    else:
                        block = generate_message(task_info, user_id)
                        client.chat_postMessage(channel=channel_id, blocks=block, text="Sending tasks!")
                        print("Send task!")
            except SlackApiError as e:
                assert e.response["ok"] is False and e.response["error"], f"Got an error: {e.response['error']}"
    log_step(logger, "send_tasks exit")


def generate_message(task_info, user_id):
    '''
    Helper function for sendTasks.
    Get the list of task assigned to a user and format them into a 
    json block message.
    Return the block message
    '''
    block = []
    starttime_format = task_info[4].strftime("%A (%m/%d) at %I:%M%p")
    # text = (f"*Task # {task_info[0]}*,Location: {task_info[2]} \n" + 
    #         f"Description: {task_info[3]}\nStart Time: {starttime_format} \n" + 
    #         f"Window: {task_info[5]} minutes \nCompensation: {task_info[6]}")
    

    text = (f"PLACEHOLDER_EMOJI *Task #PLACEHOLDER_TASKID* PLACEHOLDER_EMOJI \n*Description:* PLACEHOLDER_DESCRIPTION. \n*Start Time:* PLACEHOLDER_STARTTIME \n*Window:* PLACEHOLDER_WINDOW minutes \n*Compensation:* PLACEHOLDER_COMPENSATION")\
                .replace('PLACEHOLDER_EMOJI', EMOJI_DICT[int(str(task_info[0])[-1])]) \
                .replace('PLACEHOLDER_TASKID', str(task_info[0])) \
                .replace('PLACEHOLDER_DESCRIPTION', str(task_info[3])) \
                .replace('PLACEHOLDER_STARTTIME', str(starttime_format)) \
                .replace('PLACEHOLDER_WINDOW', str(task_info[5])) \
                .replace('PLACEHOLDER_COMPENSATION', str(task_info[6])) 

    description = {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": text
                }
    }
    buttons = button_color(task_info[0], user_id)
    block.append(description)
    block.append(buttons)
    return block


def compact_task(task_info) -> dict:
    """
    Takes a task_info list.
    Formats that task info into a compact task block (for uses outside 
        of when a task is first send to a user).
    Returns a fully formed 'section' Slack block (dict).
    """
    starttime_format = task_info[4].strftime("%A (%m/%d) at %I:%M%p")
    text  = "*Task #PLACEHOLDER_TASKID* (*comp:* PLACEHOLDER_COMPENSATION)\n *Starts:* PLACEHOLDER_STARTTIME, *window*: PLACEHOLDER_WINDOW min \n*Description:* PLACEHOLDER_DESCRIPTION." \
                .replace('PLACEHOLDER_TASKID', str(task_info[0])) \
                .replace('PLACEHOLDER_DESCRIPTION', str(task_info[3])) \
                .replace('PLACEHOLDER_STARTTIME', str(starttime_format)) \
                .replace('PLACEHOLDER_WINDOW', str(task_info[5])) \
                .replace('PLACEHOLDER_COMPENSATION', str(task_info[6])) 
    return {
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": text
			}
		}
    
def make_report_block(user_id) -> list:
    """
    Takes a user id (int? str?)
    Formats a report block for the given user using their 
        active (accepted, unexpired, uncompleted) & 
        pending (pending, unexpired) tasks.
    Returns a full formatted Slack block message (dict).
    
    """
    # A list of task_list lists for all accepted, unexpired, uncompleted tasks
    active_ids = messenger.get_accepted_tasks(user_id)
    all_active = [messenger.get_task_list(user_id, task_id) for task_id in active_ids]
  
    # A list of task_list lists for all pending & unexpired tasks
    pending_ids = messenger.get_pending_tasks(user_id)

    # Add appropriate active task information
    blocks = []
    if all_active:
        if len(blocks) >= 46:
                blocks.append(block_headers['too_many_pending_header'])
        blocks.append(block_headers['active_header'])
        blocks.append(block_headers['divider'])
        
        # Sort active tasks by start time
        sorted_active = sorted(all_active, key=lambda task_list: task_list[4]) 
        for task_list in sorted_active:
            active_task = compact_task(task_list)
            blocks.append(active_task)
    else:
        blocks.append(block_headers['no_active_header'])

    blocks.append(block_headers['divider'])
    
    # Add appropriate pending task information
    if pending_ids:
        blocks.append(block_headers['pending_header'])
    else:
        blocks.append(block_headers['no_pending_header'])

    # # Add 'for more info' ending
    # blocks.append(block_headers['divider'])
    # blocks.append(block_headers['ending_block'])

    return blocks


def button_color(task_id, user_id):
    """
    Takes a task id (int) and user id (str).
    Determines button formatting based on assignment status 
    Returns button block.
    """
    status = messenger.get_assign_status(task_id, user_id)
    if status == "rejected": # Reject btn is red
        block = copy.deepcopy(default_btn)
        block['elements'][1]['style'] = 'danger'
        block['block_id'] = str(task_id)
    elif status == "accepted": # Accept btn is green
        block = copy.deepcopy(default_btn)
        block['elements'][0]['style'] = 'primary'
        block['block_id'] = str(task_id)
    else: # both buttons grey
        block = copy.deepcopy(default_btn)
        block['block_id'] = str(task_id)
    return block

def get_all_users_info() -> dict:
    '''
    Helper function to get all users info from slack
    Takes a users array we get from slack which is a SlackResponse object type
    Returns a dict type containing same info with user id as key
    '''
    # Get users list (requires the users:read scope)
    result = client.users_list()

    # Get all user info in result
    users_array = result["members"]
    users_store = {}

    # Turn the SlackResponse object type into dict type
    for user in users_array:
        if user['deleted'] == False:
            # Key user info on their unique user ID
            user_id = user["id"]
            # Store the entire user object (you may not need all of the info)
            users_store[user_id] = user
    
    return users_store


def get_pic(url, token, user_id, task_id):
    log_step(logger, "get_pic enter", user_id=user_id, task_id=task_id)
    '''
    Takes   url: from payload['event']['files'][0]['url_private_download']
            token: the bot token
            user_id: the user who sent the picture
            task_id: the task they are trying to finish, should be payload['event']['text']
    Downloads picture with the given download url and saves it in the given path
    '''
    r = requests.get(url, headers={'Authorization': 'Bearer %s' % token})
    datetime = date.today() # change to clock
    repo_root = Path(__file__).resolve().parent.parent
    pics_dir = repo_root / "snapngo_pics"
    pics_dir.mkdir(parents=True, exist_ok=True)
    filename = str(pics_dir / f"{user_id}_{task_id}_{datetime}.jpeg")
    open(filename, 'wb').write(r.content)
    log_step(logger, "get_pic exit", filename=filename)
    return filename

def check_all_assignments():
    log_step(logger, "check_all_assignments enter")
    messenger.check_all_assignments()
    
    for user_id in messenger.get_active_users_list():
        block = [{
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": "✨*Your Daily Summary*✨"
        }
        }]
        block += generate_account_summary_block(user_id)
        #send account summary
        send_messages(user_id, block, "")
    log_step(logger, "check_all_assignments exit")
    return
    
def generate_account_summary_block(user_id):
    compensation, tasks = messenger.get_account_info(user_id)
    text = f"All completed tasks: {tasks}\nTotal compensation: {compensation} points"
    summary = [{
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": text
        }
    }]
    return summary

### ### MESSAGE HANDLERS ### ###
@app.message()
def handle_message(payload, say):
    log_step(logger, "handle_message enter", has_files="files" in payload, user=payload.get("user"))
    """
    Takes the response from a message sent in any chat in which this Bot has
        access to.
    When on, constantly listens for new messages, the responds as dictated below.
    Returns nothing.
    """
    channel_id = payload.get('channel')
    user_id = payload.get('user')
    text = payload.get('text')

    log_step(
        logger,
        "interaction message",
        user_id=user_id,
        channel=channel_id,
        text_preview=(text or "")[:80],
        has_files="files" in payload,
    )
    # Handle certain responses
    if BOT_ID != user_id:
        if 'files' not in payload:
            msg = (text or "").strip()
            if msg == "?" or msg.lower() == "help":
                log_step(logger, "interaction help", user_id=user_id)
                say(info_page)
            # User only sends text without attaching an image
            elif msg.lower() == "task":
                log_step(logger, "interaction on_demand task", user_id=user_id)
                active_users = messenger.get_active_users_list()
                if user_id not in active_users:
                    say(
                        "You need to be an active participant to get tasks. "
                        "Reply `opt in` if you have opted out."
                    )
                else:
                    tid = task.generate_on_demand_task_for_user(user_id, DB_NAME or "")
                    if tid is None:
                        say("Could not create a task right now. Please try again later.")
                    else:
                        try:
                            task_info = messenger.get_task_list(user_id, tid)
                            send_tasks({user_id: [task_info]})
                            messenger.mark_assignment_pending_for_user(tid, user_id)
                            say("Here is a new task for you. Accept or reject it above.")
                        except Exception as exc:
                            log_step(logger, "interaction on_demand task failed", error=str(exc))
                            say("Something went wrong sending your task. Please try again.")
            elif msg.lower() == "account":
                log_step(logger, "interaction account", user_id=user_id)
                send_messages(
                    user_id,
                    generate_account_summary_block(user_id),
                    "Your account summary",
                )
            elif msg.lower() == "report":
                active_block = make_report_block(user_id)
                end_block = [block_headers['divider'], block_headers['ending_block']]
                dm_channel_id = _get_dm_channel_id(user_id)
                client.chat_postMessage(channel=dm_channel_id, blocks = active_block,text="")

                 # Sort pending tasks by start time
                pending_ids = messenger.get_pending_tasks(user_id)
                all_pending = [messenger.get_task_list(user_id, task_id) for task_id in pending_ids]
                sorted_pending = sorted(all_pending, key=lambda task_list: task_list[4])
                for task_list in sorted_pending:
                    pending_task = compact_task(task_list)
                    buttons = copy.deepcopy(default_btn)
                    buttons['block_id'] = str(task_list[0])
                    blocks = [pending_task, buttons]

                    client.chat_postMessage(channel=dm_channel_id, blocks = blocks, text="")

                client.chat_postMessage(channel=dm_channel_id, blocks = end_block,text="")
            elif msg.lower() == "opt in":
                messenger.update_account_status(user_id, "active")
                say("You have opted in for the day.")
            elif msg.lower() == "opt out":
                messenger.update_account_status(user_id, "inactive")
                say("You have opted out for the day.")
            else:
                say(sample_task)
        else:
            # User attaches more than one image
            print("text+file", datetime.now())
            print(payload)
            if len(payload['files']) > 1:
                log_step(logger, "interaction reject multi_file", user_id=user_id)
                say("*:large_orange_circle: You are attaching more than one file.* Reply `?` for more information.")
                return

            # User attaches a file that is not an image
            file = payload['files'][0]
            if "image" not in file['mimetype']:
                log_step(logger, "interaction reject not_image", user_id=user_id, mimetype=file.get("mimetype"))
                say("*:large_orange_circle: The file you attached is not an image.*\n Reply `?` for more information.")
                return
            task_id = payload['blocks'][0]['elements'][0]['elements'][0]['text']
            print("TASK ID:", task_id)
            if not task_id.isdigit():
                log_step(logger, "interaction reject bad_task_text", user_id=user_id, task_text=task_id[:50])
                say(":large_orange_circle: Please include *only the task number* in the text & attach that tasks's image.")
                return
            task_id = int(task_id)
            accepted_tasks = messenger.get_accepted_tasks(user_id)
            pending_tasks = messenger.get_pending_tasks(user_id)
            # The text the user enters isn't any of their assigned task numbers
            if messenger.check_time_window(task_id) == "expired":
                log_step(logger, "interaction reject expired", user_id=user_id, task_id=task_id)
                say(f''':large_orange_circle: Task {task_id} has already expired. Please pick another assigned task to finish.''')
            elif messenger.check_time_window(task_id) == "not started":
                log_step(logger, "interaction reject not_started", user_id=user_id, task_id=task_id)
                say(f''':large_orange_circle: Task {task_id} has not started yet. Please check the start time & time window and finish this task later.''')
            elif task_id not in accepted_tasks:
                log_step(logger, "interaction reject not_accepted", user_id=user_id, task_id=task_id, accepted_tasks=accepted_tasks)
                say(f":large_orange_circle: Task {task_id} is not one of your unfinished, accepted tasks. Your unfinished, accepted tasks are {accepted_tasks}")
                if task_id in pending_tasks:
                    say(f'''However, task {task_id} is one of your pending tasks. You can still complete the task by pressing the Accept button for task {task_id} and then submit your picture.''')
                return
            else:
                log_step(logger, "interaction image submit", user_id=user_id, task_id=task_id, file=file.get("name"))
                url = file["url_private_download"]
                path = get_pic(url, BOT_TOKEN, user_id, task_id)
                log_step(logger, "interaction image saved", user_id=user_id, task_id=task_id, path=path)
                result = messenger.submit_task(user_id, task_id, path)
                if isinstance(result, dict) and result.get("ok"):
                    amt = result.get("compensation", 0)
                    again = result.get("already_submitted")
                    log_step(
                        logger,
                        "interaction submit success",
                        user_id=user_id,
                        task_id=task_id,
                        compensation_added=amt,
                        resubmission=again,
                    )
                    if again and amt == 0:
                        say(
                            f"We updated your image for task *{task_id}*. "
                            f"Compensation was already added for this task. Reply `account` to see your balance."
                        )
                    else:
                        say(
                            f"We received your submission for task *{task_id}*. "
                            f"*+{amt} points* have been added to your account right away. "
                            f"Reply `account` to see your balance and completed tasks."
                        )
                elif result is True:
                    # Backward compat if submit_task still returns bool
                    say(
                        f"We received your submission for task *{task_id}*. "
                        f"Reply `account` to see your account status."
                    )
                else:
                    log_step(logger, "interaction submit failed", user_id=user_id, task_id=task_id)
            #update database if image is NULL
        return #needs to be changed


@app.event("message")
def handle_message_events(body, logger, say):
    '''
    When user only send a picture without text
    '''
    logger.info(body)
    user = body['event']['user']
    say(sample_task)


@app.event("file_shared")
def handle_file_shared_events():
    '''
    Don't need this. Just added it so we don't get warning messages from it.
    '''
    return

@app.event("team_join")
def handle_team_join(body, logger, say):
    user_store = get_all_users_info()
    messenger.add_users(user_store)
    user_id = body["event"]["user"]["id"]
    send_welcome_message([user_id])

### ### INTERACTION HANDLERS ### ###
def _get_verification_comment(body):
    try:
        return body["state"]["values"]["verification_comment"]["verification_comment_input"]["value"]
    except Exception:
        return None


@app.action("verify_agree")
def handle_verification_agree(body, ack, say):
    ack()
    log_step(logger, "interaction verify_agree", user_id=body.get("user", {}).get("id"))
    value = body["actions"][0]["value"]
    _, feedback_task_id, _ = value.split(":")
    comment = _get_verification_comment(body)
    user_id = body["user"]["id"]
    feedback_collector.process_feedback_response(
        user_id=user_id,
        feedback_task_id=int(feedback_task_id),
        agrees=True,
        comment=comment,
    )
    say("Thanks for reviewing Gemini's decision!")


@app.action("verify_disagree")
def handle_verification_disagree(body, ack, say):
    ack()
    log_step(logger, "interaction verify_disagree", user_id=body.get("user", {}).get("id"))
    value = body["actions"][0]["value"]
    _, feedback_task_id, _ = value.split(":")
    comment = _get_verification_comment(body)
    user_id = body["user"]["id"]
    feedback_collector.process_feedback_response(
        user_id=user_id,
        feedback_task_id=int(feedback_task_id),
        agrees=False,
        comment=comment,
    )
    say("Thanks for your feedback. We recorded your response.")


@app.action("accepted")
def action_button_click(body, ack, say):
    '''
    body['actions'][0]   {'value': 'accepted', 'block_id': '1', 'type': 'button', 'action_id': 'accepted', 'text':...}
    '''
    # Acknowledge the action
    ack()
    messenger.update_tasks_expired()
    action = body['actions'][0]
    new_status = action['value']
    task = int(action['block_id'])
    user = str(body['user']['id'])
    task_list = messenger.get_task_list(user, task)
    old_status = messenger.get_assign_status(task, user)
    if messenger.check_time_window(task) == "expired":
        say(f''':large_orange_circle: Task {task} has already expired. Please pick another assigned task to finish.''')
        return
    if old_status == "pending":
        messenger.update_assign_status(new_status, task, user)
        # task_list = messenger.get
        message = generate_message(task_list, user)
        client.chat_update(channel=body["channel"]["id"], ts = body["message"]["ts"], blocks = message,text="Accepted!")
        say(f"You {new_status} task {task}")
    else:
        say(f"You already {old_status} task {task}")
    return
    

@app.action("rejected")
def action_button_click(body, ack, say):
    # Acknowledge the action
    ack()

    # Get task info 
    messenger.update_tasks_expired()
    action = body['actions'][0]
    new_status = action['value']
    task = int(action['block_id'])
    user = str(body['user']['id'])
    task_list = messenger.get_task_list(user, task)
    old_status = messenger.get_assign_status(task, user)
    if messenger.check_time_window(task) == "expired":
        say(f''':large_orange_circle: Task {task} has already expired.''')
        return
    # Change 
    if old_status == "pending":
        messenger.update_assign_status(new_status, task, user)
        # task_list = messenger.get
        message = generate_message(task_list, user)
        client.chat_update(channel=body["channel"]["id"], ts = body["message"]["ts"], blocks = message,text="Rejected!")
        say(
            f"You {new_status} task {task}. No compensation for rejecting. "
            f"Reply `account` to see your balance."
        )
    else:
        say(f"You already {old_status} task {task}")
    return


@app.action("bugs_form")
def handle_some_action(ack, body, logger):
    ack()
    logger.info(body)


if __name__ == "__main__":
    # Start bolt socket handler
    SocketModeHandler(app, SLACK_APP_TOKEN).start()
